
import { Category, Difficulty, Recipe } from './types';

// Helper de imágenes
const getImg = (term: string) => `https://picsum.photos/seed/${term}/800/600`;

export const SAMPLE_RECIPES: Recipe[] = [
  // ===========================================================================
  // APERITIVOS (40 Recetas)
  // ===========================================================================
  {
    id: 'nav_ap_001',
    title: 'Gambones al Ajillo',
    description: 'Clásico picante y jugoso.',
    category: Category.APERITIVO,
    imageUrl: getImg('gambones'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'gambones', amount: 16, unit: 'ud' }, { name: 'ajos', amount: 4, unit: 'ud' }, { name: 'guindilla', amount: 1, unit: 'ud' }],
    steps: [{ order: 1, description: 'Laminar ajos.' }, { order: 2, description: 'Dorar ajos y guindilla.' }, { order: 3, description: 'Saltear gambones.' }],
    tags: ['sin gluten', 'marisco']
  },
  {
    id: 'nav_ap_002',
    title: 'Canapés de Queso y Cebolla',
    description: 'Dulce y salado en un bocado.',
    category: Category.APERITIVO,
    imageUrl: getImg('canape1'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'pan tostado', amount: 12, unit: 'ud' }, { name: 'queso cabra', amount: 200, unit: 'g' }, { name: 'cebolla caramelizada', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Poner queso sobre pan.' }, { order: 2, description: 'Coronar con cebolla.' }],
    tags: ['vegetariano']
  },
  {
    id: 'nav_ap_003',
    title: 'Dátiles con Bacon',
    description: 'Crujiente y dulce.',
    category: Category.APERITIVO,
    imageUrl: getImg('dates'),
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'dátiles', amount: 12, unit: 'ud' }, { name: 'bacon', amount: 12, unit: 'lonchas' }],
    steps: [{ order: 1, description: 'Envolver dátil en bacon.' }, { order: 2, description: 'Hornear hasta dorar.' }],
    tags: ['carne', 'sin gluten']
  },
  {
    id: 'nav_ap_004',
    title: 'Huevos Rellenos Festivos',
    description: 'Con atún y pimiento.',
    category: Category.APERITIVO,
    imageUrl: getImg('eggs'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 10,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'huevos', amount: 6, unit: 'ud' }, { name: 'atún', amount: 2, unit: 'latas' }, { name: 'mayonesa', amount: 4, unit: 'cucharadas' }],
    steps: [{ order: 1, description: 'Cocer huevos.' }, { order: 2, description: 'Mezclar yemas con atún.' }, { order: 3, description: 'Rellenar.' }],
    tags: ['frio']
  },
  {
    id: 'nav_ap_005',
    title: 'Croquetas de Jamón',
    description: 'Cremosas y tradicionales.',
    category: Category.APERITIVO,
    imageUrl: getImg('croquetas'),
    prepTimeMinutes: 40,
    cookTimeMinutes: 15,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'jamón serrano', amount: 150, unit: 'g' }, { name: 'leche', amount: 500, unit: 'ml' }, { name: 'harina', amount: 50, unit: 'g' }],
    steps: [{ order: 1, description: 'Hacer bechamel con jamón.' }, { order: 2, description: 'Enfriar, bolear y freír.' }],
    tags: ['tradicional']
  },
  {
    id: 'nav_ap_006',
    title: 'Rollitos de Salmón',
    description: 'Con queso crema.',
    category: Category.APERITIVO,
    imageUrl: getImg('salmonroll'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'salmón ahumado', amount: 200, unit: 'g' }, { name: 'queso crema', amount: 150, unit: 'g' }],
    steps: [{ order: 1, description: 'Untar queso en salmón.' }, { order: 2, description: 'Enrollar y cortar.' }],
    tags: ['frio', 'sin gluten']
  },
  {
    id: 'nav_ap_007',
    title: 'Gulas al Ajillo',
    description: 'Sencillo y sabroso.',
    category: Category.APERITIVO,
    imageUrl: getImg('gulas'),
    prepTimeMinutes: 5,
    cookTimeMinutes: 5,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'gulas', amount: 250, unit: 'g' }, { name: 'ajo', amount: 2, unit: 'dientes' }, { name: 'guindilla', amount: 1, unit: 'ud' }],
    steps: [{ order: 1, description: 'Dorar ajos.' }, { order: 2, description: 'Saltear gulas.' }],
    tags: ['pescado']
  },
  {
    id: 'nav_ap_008',
    title: 'Tabla de Ibéricos',
    description: 'Selección de curados.',
    category: Category.APERITIVO,
    imageUrl: getImg('ibericos'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'jamón ibérico', amount: 100, unit: 'g' }, { name: 'chorizo', amount: 100, unit: 'g' }, { name: 'queso manchego', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Cortar y disponer en tabla.' }],
    tags: ['frio', 'sin gluten']
  },
  {
    id: 'nav_ap_009',
    title: 'Champiñones Rellenos',
    description: 'Con virutas de jamón.',
    category: Category.APERITIVO,
    imageUrl: getImg('mushrooms'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'champiñones grandes', amount: 8, unit: 'ud' }, { name: 'jamón', amount: 50, unit: 'g' }, { name: 'ajo', amount: 1, unit: 'diente' }],
    steps: [{ order: 1, description: 'Limpiar sombreros.' }, { order: 2, description: 'Rellenar con picada de tallos y jamón.' }, { order: 3, description: 'Hornear.' }],
    tags: ['caliente']
  },
  {
    id: 'nav_ap_010',
    title: 'Tostas de Sobrasada y Miel',
    description: 'Mallorca en la mesa.',
    category: Category.APERITIVO,
    imageUrl: getImg('sobrasada'),
    prepTimeMinutes: 5,
    cookTimeMinutes: 5,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'pan', amount: 4, unit: 'rebanadas' }, { name: 'sobrasada', amount: 100, unit: 'g' }, { name: 'miel', amount: 2, unit: 'cucharadas' }],
    steps: [{ order: 1, description: 'Untar sobrasada.' }, { order: 2, description: 'Gratinar.' }, { order: 3, description: 'Añadir miel.' }],
    tags: ['caliente']
  },
  {
    id: 'nav_ap_011',
    title: 'Volovanes de Marisco',
    description: 'Hojaldre relleno.',
    category: Category.APERITIVO,
    imageUrl: getImg('volovan'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'volovanes', amount: 8, unit: 'ud' }, { name: 'gambas', amount: 100, unit: 'g' }, { name: 'bechamel', amount: 100, unit: 'ml' }],
    steps: [{ order: 1, description: 'Mezclar gambas salteadas con bechamel.' }, { order: 2, description: 'Rellenar y hornear.' }],
    tags: ['marisco']
  },
  {
    id: 'nav_ap_012',
    title: 'Pinchos de Tortilla',
    description: 'Español 100%.',
    category: Category.APERITIVO,
    imageUrl: getImg('tortilla'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'huevos', amount: 4, unit: 'ud' }, { name: 'patatas', amount: 2, unit: 'ud' }, { name: 'cebolla', amount: 1, unit: 'ud' }],
    steps: [{ order: 1, description: 'Freír patata y cebolla.' }, { order: 2, description: 'Cuajar tortilla.' }, { order: 3, description: 'Cortar en cubos.' }],
    tags: ['vegetariano', 'sin gluten']
  },
  {
    id: 'nav_ap_013',
    title: 'Mejillones Tigre',
    description: 'Rellenos y picantes.',
    category: Category.APERITIVO,
    imageUrl: getImg('tigres'),
    prepTimeMinutes: 30,
    cookTimeMinutes: 20,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'mejillones', amount: 500, unit: 'g' }, { name: 'bechamel', amount: 200, unit: 'ml' }, { name: 'pan rallado', amount: 50, unit: 'g' }],
    steps: [{ order: 1, description: 'Cocer mejillones.' }, { order: 2, description: 'Hacer masa con carne y bechamel picante.' }, { order: 3, description: 'Rellenar conchas, empanar y freír.' }],
    tags: ['marisco']
  },
  {
    id: 'nav_ap_014',
    title: 'Brochetas de Cherry y Mozzarella',
    description: 'Caprese en palito.',
    category: Category.APERITIVO,
    imageUrl: getImg('caprese'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'tomates cherry', amount: 12, unit: 'ud' }, { name: 'perlas mozzarella', amount: 12, unit: 'ud' }, { name: 'albahaca', amount: 12, unit: 'hojas' }],
    steps: [{ order: 1, description: 'Ensartar tomate, queso y albahaca.' }, { order: 2, description: 'Aliñar con pesto.' }],
    tags: ['vegetariano', 'frio']
  },
  {
    id: 'nav_ap_015',
    title: 'Almejas a la Marinera',
    description: 'Salsa para mojar pan.',
    category: Category.APERITIVO,
    imageUrl: getImg('clams'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'almejas', amount: 500, unit: 'g' }, { name: 'cebolla', amount: 1, unit: 'ud' }, { name: 'vino blanco', amount: 100, unit: 'ml' }, { name: 'pimentón', amount: 1, unit: 'cucharadita' }],
    steps: [{ order: 1, description: 'Sofreír cebolla y pimentón.' }, { order: 2, description: 'Añadir vino y almejas hasta abrir.' }],
    tags: ['marisco']
  },
  {
    id: 'nav_ap_016',
    title: 'Paté de Centollo (Falso)',
    description: 'Sabor a marisco fácil.',
    category: Category.APERITIVO,
    imageUrl: getImg('pate'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'mejillones lata', amount: 1, unit: 'lata' }, { name: 'anchoas', amount: 6, unit: 'ud' }, { name: 'palitos cangrejo', amount: 6, unit: 'ud' }, { name: 'mayonesa', amount: 2, unit: 'cucharadas' }],
    steps: [{ order: 1, description: 'Triturar todo junto.' }, { order: 2, description: 'Servir con tostas.' }],
    tags: ['rapido']
  },
  {
    id: 'nav_ap_017',
    title: 'Espárragos con Mayonesa',
    description: 'Navarra en el plato.',
    category: Category.APERITIVO,
    imageUrl: getImg('asparagus'),
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'espárragos blancos', amount: 8, unit: 'ud' }, { name: 'mayonesa', amount: 4, unit: 'cucharadas' }],
    steps: [{ order: 1, description: 'Escurrir y emplatar con salsa.' }],
    tags: ['vegetariano', 'frio']
  },
  {
    id: 'nav_ap_018',
    title: 'Pulpo a la Gallega',
    description: 'Fiesta asegurada.',
    category: Category.APERITIVO,
    imageUrl: getImg('octopus'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'patas pulpo cocido', amount: 2, unit: 'ud' }, { name: 'patatas cocidas', amount: 2, unit: 'ud' }, { name: 'pimentón', amount: 1, unit: 'cucharada' }, { name: 'aceite oliva', amount: 50, unit: 'ml' }],
    steps: [{ order: 1, description: 'Cortar patatas y pulpo.' }, { order: 2, description: 'Calentar ligeramente.' }, { order: 3, description: 'Espolvorear sal, pimentón y aceite.' }],
    tags: ['tradicional', 'sin gluten']
  },
  {
    id: 'nav_ap_019',
    title: 'Boquerones en Vinagre',
    description: 'Aperitivo castizo.',
    category: Category.APERITIVO,
    imageUrl: getImg('anchovies'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 0,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'boquerones', amount: 300, unit: 'g' }, { name: 'vinagre', amount: 200, unit: 'ml' }, { name: 'ajo y perejil', amount: 1, unit: 'picada' }],
    steps: [{ order: 1, description: 'Limpiar y congelar boquerones.' }, { order: 2, description: 'Marinar en vinagre 4 horas.' }, { order: 3, description: 'Aliñar con aceite, ajo y perejil.' }],
    tags: ['pescado', 'frio']
  },
  {
    id: 'nav_ap_020',
    title: 'Brandada de Bacalao',
    description: 'Crema suave para untar.',
    category: Category.APERITIVO,
    imageUrl: getImg('brandade'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'bacalao desalado', amount: 300, unit: 'g' }, { name: 'ajo', amount: 2, unit: 'dientes' }, { name: 'aceite oliva', amount: 100, unit: 'ml' }, { name: 'nata', amount: 50, unit: 'ml' }],
    steps: [{ order: 1, description: 'Confitar bacalao con ajos.' }, { order: 2, description: 'Triturar emulsionando con el aceite y nata.' }],
    tags: ['pescado']
  },
  {
    id: 'nav_ap_021',
    title: 'Empanadillas de Bonito',
    description: 'Crujientes y caseras.',
    category: Category.APERITIVO,
    imageUrl: getImg('empanadillas'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 15,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'obleas', amount: 16, unit: 'ud' }, { name: 'bonito', amount: 2, unit: 'latas' }, { name: 'tomate frito', amount: 4, unit: 'cucharadas' }, { name: 'huevo duro', amount: 1, unit: 'ud' }],
    steps: [{ order: 1, description: 'Mezclar relleno.' }, { order: 2, description: 'Rellenar obleas y cerrar.' }, { order: 3, description: 'Freír u hornear.' }],
    tags: ['tradicional']
  },
  {
    id: 'nav_ap_022',
    title: 'Tartaletas de Foie',
    description: 'Lujo en miniatura.',
    category: Category.APERITIVO,
    imageUrl: getImg('foie'),
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'tartaletas', amount: 8, unit: 'ud' }, { name: 'mousse de pato', amount: 100, unit: 'g' }, { name: 'mermelada frambuesa', amount: 4, unit: 'cucharaditas' }],
    steps: [{ order: 1, description: 'Rellenar con foie.' }, { order: 2, description: 'Toque de mermelada.' }],
    tags: ['frio']
  },
  {
    id: 'nav_ap_023',
    title: 'Aceitunas Aliñadas',
    description: 'El picoteo básico.',
    category: Category.APERITIVO,
    imageUrl: getImg('olives'),
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'aceitunas', amount: 200, unit: 'g' }, { name: 'limón', amount: 1, unit: 'trozos' }, { name: 'tomillo', amount: 1, unit: 'rama' }],
    steps: [{ order: 1, description: 'Mezclar todo y dejar macerar.' }],
    tags: ['vegano', 'rapido']
  },
  {
    id: 'nav_ap_024',
    title: 'Blinis con Caviar (Sucedáneo)',
    description: 'Toque ruso.',
    category: Category.APERITIVO,
    imageUrl: getImg('blinis'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'blinis', amount: 8, unit: 'ud' }, { name: 'crema agria', amount: 4, unit: 'cucharadas' }, { name: 'huevas negras', amount: 50, unit: 'g' }],
    steps: [{ order: 1, description: 'Poner crema sobre blini.' }, { order: 2, description: 'Coronar con huevas.' }],
    tags: ['frio']
  },
  {
    id: 'nav_ap_025',
    title: 'Croquetas de Boletus',
    description: 'Sabor a bosque.',
    category: Category.APERITIVO,
    imageUrl: getImg('boletuscroq'),
    prepTimeMinutes: 40,
    cookTimeMinutes: 20,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'boletus', amount: 150, unit: 'g' }, { name: 'leche', amount: 500, unit: 'ml' }, { name: 'harina', amount: 50, unit: 'g' }],
    steps: [{ order: 1, description: 'Sofreír setas.' }, { order: 2, description: 'Hacer bechamel con ellas.' }, { order: 3, description: 'Enfriar, empanar y freír.' }],
    tags: ['vegetariano']
  },
  {
    id: 'nav_ap_026',
    title: 'Vieiras Gratinadas',
    description: 'Elegancia gallega.',
    category: Category.APERITIVO,
    imageUrl: getImg('scallops'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'vieiras', amount: 4, unit: 'ud' }, { name: 'cebolla', amount: 1, unit: 'ud' }, { name: 'jamón', amount: 50, unit: 'g' }, { name: 'pan rallado', amount: 2, unit: 'cucharadas' }],
    steps: [{ order: 1, description: 'Sofreír cebolla y jamón.' }, { order: 2, description: 'Cubrir vieira en concha.' }, { order: 3, description: 'Espolvorear pan y gratinar.' }],
    tags: ['marisco']
  },
  {
    id: 'nav_ap_027',
    title: 'Pimientos del Piquillo Rellenos',
    description: 'De bacalao o carne.',
    category: Category.APERITIVO,
    imageUrl: getImg('peppers'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 20,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'piquillos', amount: 8, unit: 'ud' }, { name: 'relleno (carne/pescado)', amount: 200, unit: 'g' }, { name: 'salsa piquillo', amount: 100, unit: 'ml' }],
    steps: [{ order: 1, description: 'Rellenar pimientos.' }, { order: 2, description: 'Calentar en salsa.' }],
    tags: ['tradicional']
  },
  {
    id: 'nav_ap_028',
    title: 'Guacamole con Nachos',
    description: 'Toque exótico.',
    category: Category.APERITIVO,
    imageUrl: getImg('guacamole'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'aguacates', amount: 2, unit: 'ud' }, { name: 'tomate', amount: 1, unit: 'ud' }, { name: 'cebolla', amount: 0.5, unit: 'ud' }, { name: 'nachos', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Machacar aguacate.' }, { order: 2, description: 'Mezclar con verduras picadas y lima.' }],
    tags: ['vegano']
  },
  {
    id: 'nav_ap_029',
    title: 'Chistorra a la Sidra',
    description: 'Navarra y País Vasco.',
    category: Category.APERITIVO,
    imageUrl: getImg('chistorra'),
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'chistorra', amount: 1, unit: 'pieza' }, { name: 'sidra', amount: 100, unit: 'ml' }],
    steps: [{ order: 1, description: 'Trocear chistorra.' }, { order: 2, description: 'Cocer en sidra 15 min.' }],
    tags: ['carne']
  },
  {
    id: 'nav_ap_030',
    title: 'Queso Provolone al Horno',
    description: 'Para compartir.',
    category: Category.APERITIVO,
    imageUrl: getImg('provolone'),
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'provolone', amount: 1, unit: 'rodaja' }, { name: 'tomate frito', amount: 2, unit: 'cucharadas' }, { name: 'orégano', amount: 1, unit: 'pizca' }],
    steps: [{ order: 1, description: 'Poner tomate en cazuela, queso encima.' }, { order: 2, description: 'Hornear hasta fundir.' }],
    tags: ['vegetariano']
  },
  {
    id: 'nav_ap_031',
    title: 'Rollitos de Primavera',
    description: 'Crujiente asiático.',
    category: Category.APERITIVO,
    imageUrl: getImg('springroll'),
    prepTimeMinutes: 30,
    cookTimeMinutes: 10,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'masa rollito', amount: 8, unit: 'hojas' }, { name: 'repollo', amount: 100, unit: 'g' }, { name: 'zanahoria', amount: 1, unit: 'ud' }, { name: 'carne picada', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Saltear relleno.' }, { order: 2, description: 'Enrollar en masa.' }, { order: 3, description: 'Freír.' }],
    tags: ['internacional']
  },
  {
    id: 'nav_ap_032',
    title: 'Ensaladilla Rusa (Tapa)',
    description: 'Imprescindible.',
    category: Category.APERITIVO,
    imageUrl: getImg('ensaladilla'),
    prepTimeMinutes: 30,
    cookTimeMinutes: 20,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'patatas', amount: 2, unit: 'ud' }, { name: 'zanahoria', amount: 1, unit: 'ud' }, { name: 'atún', amount: 1, unit: 'lata' }, { name: 'mayonesa', amount: 3, unit: 'cucharadas' }],
    steps: [{ order: 1, description: 'Cocer verduras en dados.' }, { order: 2, description: 'Mezclar con atún y mayonesa.' }],
    tags: ['frio', 'sin gluten']
  },
  {
    id: 'nav_ap_033',
    title: 'Hummus con Crudités',
    description: 'Sano y ligero.',
    category: Category.APERITIVO,
    imageUrl: getImg('hummus'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'garbanzos cocidos', amount: 400, unit: 'g' }, { name: 'tahini', amount: 1, unit: 'cucharada' }, { name: 'zanahoria', amount: 2, unit: 'ud' }],
    steps: [{ order: 1, description: 'Triturar garbanzos, tahini, limón y ajo.' }, { order: 2, description: 'Servir con bastones de zanahoria.' }],
    tags: ['vegano']
  },
  {
    id: 'nav_ap_034',
    title: 'Salmón Marinado',
    description: 'Casero y delicioso.',
    category: Category.APERITIVO,
    imageUrl: getImg('gravlax'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 0,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'lomo salmón fresco', amount: 500, unit: 'g' }, { name: 'sal gorda', amount: 200, unit: 'g' }, { name: 'azúcar', amount: 200, unit: 'g' }, { name: 'eneldo', amount: 1, unit: 'manojo' }],
    steps: [{ order: 1, description: 'Cubrir salmón con mezcla sal/azúcar/eneldo.' }, { order: 2, description: 'Reposar 24h en nevera con peso.' }, { order: 3, description: 'Limpiar y laminar.' }],
    tags: ['pescado', 'sin gluten']
  },
  {
    id: 'nav_ap_035',
    title: 'Tacos de Jamón y Queso',
    description: 'Sencillez.',
    category: Category.APERITIVO,
    imageUrl: getImg('cheeseham'),
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'queso semi', amount: 200, unit: 'g' }, { name: 'jamón york taco', amount: 200, unit: 'g' }],
    steps: [{ order: 1, description: 'Cortar en dados iguales.' }, { order: 2, description: 'Servir con palillos.' }],
    tags: ['sin gluten', 'rapido']
  },
  {
    id: 'nav_ap_036',
    title: 'Mini Pizzas',
    description: 'Gusta a los niños.',
    category: Category.APERITIVO,
    imageUrl: getImg('minipizza'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'masa pizza', amount: 1, unit: 'base' }, { name: 'tomate', amount: 4, unit: 'cucharadas' }, { name: 'mozzarella', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Cortar círculos.' }, { order: 2, description: 'Poner ingredientes.' }, { order: 3, description: 'Hornear.' }],
    tags: ['niños']
  },
  {
    id: 'nav_ap_037',
    title: 'Bastones de Berenjena con Miel',
    description: 'Crujiente andaluz.',
    category: Category.APERITIVO,
    imageUrl: getImg('eggplant'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'berenjena', amount: 1, unit: 'ud' }, { name: 'harina', amount: 100, unit: 'g' }, { name: 'miel de caña', amount: 2, unit: 'cucharadas' }],
    steps: [{ order: 1, description: 'Cortar bastones y enharinar.' }, { order: 2, description: 'Freír.' }, { order: 3, description: 'Rociar miel.' }],
    tags: ['vegetariano']
  },
  {
    id: 'nav_ap_038',
    title: 'Nachos con Queso',
    description: 'Tex-Mex.',
    category: Category.APERITIVO,
    imageUrl: getImg('nachos'),
    prepTimeMinutes: 5,
    cookTimeMinutes: 5,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'tortillas maíz', amount: 200, unit: 'g' }, { name: 'salsa queso', amount: 100, unit: 'ml' }, { name: 'jalapeños', amount: 1, unit: 'puñado' }],
    steps: [{ order: 1, description: 'Calentar salsa.' }, { order: 2, description: 'Verter sobre nachos.' }],
    tags: ['rapido']
  },
  {
    id: 'nav_ap_039',
    title: 'Cucharitas de Ceviche',
    description: 'Fresco y ácido.',
    category: Category.APERITIVO,
    imageUrl: getImg('ceviche'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 0,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'pescado blanco', amount: 200, unit: 'g' }, { name: 'limas', amount: 3, unit: 'ud' }, { name: 'cebolla morada', amount: 0.5, unit: 'ud' }, { name: 'cilantro', amount: 1, unit: 'puñado' }],
    steps: [{ order: 1, description: 'Macerar pescado en lima 15 min.' }, { order: 2, description: 'Mezclar con cebolla y cilantro.' }],
    tags: ['sin gluten', 'pescado']
  },
  {
    id: 'nav_ap_040',
    title: 'Bombones de Morcilla',
    description: 'Sorpresa crujiente.',
    category: Category.APERITIVO,
    imageUrl: getImg('blackpudding'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 10,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'morcilla', amount: 1, unit: 'ud' }, { name: 'almendra granillo', amount: 50, unit: 'g' }, { name: 'huevo', amount: 1, unit: 'ud' }],
    steps: [{ order: 1, description: 'Desmigar morcilla y hacer bolas.' }, { order: 2, description: 'Pasar por huevo y almendra.' }, { order: 3, description: 'Freír u hornear.' }],
    tags: ['carne']
  },

  // ===========================================================================
  // PRIMEROS (40 Recetas)
  // ===========================================================================
  {
    id: 'nav_pr_001',
    title: 'Sopa de Galets (Escudella)',
    description: 'Tradición catalana.',
    category: Category.PRIMERO,
    imageUrl: getImg('galets'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 120,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'caldo carne', amount: 2, unit: 'l' }, { name: 'galets', amount: 300, unit: 'g' }, { name: 'carne picada', amount: 200, unit: 'g' }],
    steps: [{ order: 1, description: 'Hacer pelotas de carne.' }, { order: 2, description: 'Cocer pasta y carne en caldo.' }],
    tags: ['tradicional', 'cuchara']
  },
  {
    id: 'nav_pr_002',
    title: 'Crema de Marisco',
    description: 'Intensa.',
    category: Category.PRIMERO,
    imageUrl: getImg('seafoodsoup'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 40,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'gambones', amount: 12, unit: 'ud' }, { name: 'verduras', amount: 300, unit: 'g' }, { name: 'nata', amount: 100, unit: 'ml' }],
    steps: [{ order: 1, description: 'Sofreír cáscaras y verduras.' }, { order: 2, description: 'Cocer, triturar y colar.' }, { order: 3, description: 'Añadir nata.' }],
    tags: ['marisco']
  },
  {
    id: 'nav_pr_003',
    title: 'Lombarda con Manzana',
    description: 'Madrid en Nochebuena.',
    category: Category.PRIMERO,
    imageUrl: getImg('lombarda'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'lombarda', amount: 1, unit: 'ud' }, { name: 'manzana', amount: 2, unit: 'ud' }, { name: 'piñones', amount: 30, unit: 'g' }],
    steps: [{ order: 1, description: 'Cocer lombarda.' }, { order: 2, description: 'Saltear con manzana y piñones.' }],
    tags: ['vegano', 'saludable']
  },
  {
    id: 'nav_pr_004',
    title: 'Consomé al Jerez',
    description: 'Reconfortante.',
    category: Category.PRIMERO,
    imageUrl: getImg('consome'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 180,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'huesos y carne', amount: 1, unit: 'kg' }, { name: 'verduras caldo', amount: 500, unit: 'g' }, { name: 'vino jerez', amount: 50, unit: 'ml' }],
    steps: [{ order: 1, description: 'Cocer todo 3h.' }, { order: 2, description: 'Clarificar y añadir jerez.' }],
    tags: ['tradicional']
  },
  {
    id: 'nav_pr_005',
    title: 'Cardo con Almendras',
    description: 'Navarra y Aragón.',
    category: Category.PRIMERO,
    imageUrl: getImg('cardo'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'cardo conserva', amount: 800, unit: 'g' }, { name: 'almendra molida', amount: 50, unit: 'g' }, { name: 'leche', amount: 200, unit: 'ml' }],
    steps: [{ order: 1, description: 'Hacer salsa con almendra y leche.' }, { order: 2, description: 'Cocer cardo en salsa.' }],
    tags: ['vegetariano']
  },
  {
    id: 'nav_pr_006',
    title: 'Sopa de Pescado',
    description: 'Sabor a mar.',
    category: Category.PRIMERO,
    imageUrl: getImg('fishsoup'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 40,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'pescado roca', amount: 500, unit: 'g' }, { name: 'almejas', amount: 200, unit: 'g' }, { name: 'fideo fino', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Hacer fumet.' }, { order: 2, description: 'Sofreír carne pescado.' }, { order: 3, description: 'Juntar y cocer fideos.' }],
    tags: ['pescado', 'cuchara']
  },
  {
    id: 'nav_pr_007',
    title: 'Vichyssoise',
    description: 'Crema fría de puerros.',
    category: Category.PRIMERO,
    imageUrl: getImg('vichyssoise'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'puerros', amount: 4, unit: 'ud' }, { name: 'patatas', amount: 2, unit: 'ud' }, { name: 'nata', amount: 200, unit: 'ml' }],
    steps: [{ order: 1, description: 'Pochar puerro y patata.' }, { order: 2, description: 'Cocer, triturar con nata y enfriar.' }],
    tags: ['vegetariano', 'frio']
  },
  {
    id: 'nav_pr_008',
    title: 'Ensalada de Escarola y Granada',
    description: 'Frescor invernal.',
    category: Category.PRIMERO,
    imageUrl: getImg('pomegranate'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'escarola', amount: 1, unit: 'ud' }, { name: 'granada', amount: 1, unit: 'ud' }, { name: 'ajo', amount: 1, unit: 'diente' }],
    steps: [{ order: 1, description: 'Limpiar escarola.' }, { order: 2, description: 'Desgranar fruta.' }, { order: 3, description: 'Aliñar con ajo frotado.' }],
    tags: ['vegano', 'saludable']
  },
  {
    id: 'nav_pr_009',
    title: 'Canelones de San Esteban',
    description: 'Aprovechamiento de lujo (Cataluña).',
    category: Category.PRIMERO,
    imageUrl: getImg('cannelloni'),
    prepTimeMinutes: 40,
    cookTimeMinutes: 40,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'placas canelones', amount: 16, unit: 'ud' }, { name: 'restos carne', amount: 400, unit: 'g' }, { name: 'bechamel', amount: 500, unit: 'ml' }],
    steps: [{ order: 1, description: 'Picar carne asada.' }, { order: 2, description: 'Rellenar pasta cocida.' }, { order: 3, description: 'Cubrir bechamel y gratinar.' }],
    tags: ['tradicional']
  },
  {
    id: 'nav_pr_010',
    title: 'Sopa de Picadillo',
    description: 'Andaluza.',
    category: Category.PRIMERO,
    imageUrl: getImg('picadillo'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'caldo pollo', amount: 1.5, unit: 'l' }, { name: 'jamón picado', amount: 100, unit: 'g' }, { name: 'huevo duro', amount: 2, unit: 'ud' }, { name: 'fideos', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Calentar caldo.' }, { order: 2, description: 'Cocer fideos.' }, { order: 3, description: 'Servir con jamón y huevo picados.' }],
    tags: ['rapido', 'cuchara']
  },
  {
    id: 'nav_pr_011',
    title: 'Crema de Calabaza y Naranja',
    description: 'Toque cítrico.',
    category: Category.PRIMERO,
    imageUrl: getImg('pumpkin'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'calabaza', amount: 600, unit: 'g' }, { name: 'naranja', amount: 1, unit: 'ud' }, { name: 'jengibre', amount: 1, unit: 'trozo' }],
    steps: [{ order: 1, description: 'Cocer calabaza.' }, { order: 2, description: 'Triturar con zumo y jengibre.' }],
    tags: ['vegano']
  },
  {
    id: 'nav_pr_012',
    title: 'Espárragos Trigueros a la Plancha',
    description: 'Ligero antes del festín.',
    category: Category.PRIMERO,
    imageUrl: getImg('greenasparagus'),
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'espárragos trigueros', amount: 2, unit: 'manojos' }, { name: 'sal gorda', amount: 1, unit: 'pizca' }, { name: 'aceite', amount: 2, unit: 'cucharadas' }],
    steps: [{ order: 1, description: 'Cortar parte dura.' }, { order: 2, description: 'Hacer a la plancha.' }],
    tags: ['vegano', 'saludable']
  },
  {
    id: 'nav_pr_013',
    title: 'Sopa Castellana (Ajo)',
    description: 'Humilde y deliciosa.',
    category: Category.PRIMERO,
    imageUrl: getImg('garlicsoup'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'pan duro', amount: 200, unit: 'g' }, { name: 'ajo', amount: 6, unit: 'dientes' }, { name: 'pimentón', amount: 1, unit: 'cucharada' }, { name: 'huevos', amount: 4, unit: 'ud' }],
    steps: [{ order: 1, description: 'Dorar ajos y pan.' }, { order: 2, description: 'Añadir pimentón y agua.' }, { order: 3, description: 'Escalfar huevos al final.' }],
    tags: ['tradicional', 'cuchara']
  },
  {
    id: 'nav_pr_014',
    title: 'Habitas con Jamón',
    description: 'Fino y sabroso.',
    category: Category.PRIMERO,
    imageUrl: getImg('broadbeans'),
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'habitas baby aceite', amount: 2, unit: 'botes' }, { name: 'jamón', amount: 100, unit: 'g' }, { name: 'cebolleta', amount: 1, unit: 'ud' }],
    steps: [{ order: 1, description: 'Pochar cebolleta.' }, { order: 2, description: 'Añadir habitas y jamón brevemente.' }],
    tags: ['rapido', 'sin gluten']
  },
  {
    id: 'nav_pr_015',
    title: 'Risotto de Setas',
    description: 'Cremoso italiano.',
    category: Category.PRIMERO,
    imageUrl: getImg('risotto'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'arroz arboreo', amount: 300, unit: 'g' }, { name: 'setas variadas', amount: 300, unit: 'g' }, { name: 'caldo', amount: 1, unit: 'l' }, { name: 'parmesano', amount: 50, unit: 'g' }],
    steps: [{ order: 1, description: 'Sofreír setas y arroz.' }, { order: 2, description: 'Añadir caldo poco a poco removiendo.' }, { order: 3, description: 'Mantecar con queso.' }],
    tags: ['vegetariano', 'arroz']
  },
  {
    id: 'nav_pr_016',
    title: 'Pastel de Cabracho',
    description: 'Untable de pescado.',
    category: Category.PRIMERO,
    imageUrl: getImg('fishcake'),
    prepTimeMinutes: 30,
    cookTimeMinutes: 45,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'cabracho cocido', amount: 400, unit: 'g' }, { name: 'huevos', amount: 4, unit: 'ud' }, { name: 'nata', amount: 200, unit: 'ml' }, { name: 'tomate frito', amount: 4, unit: 'cucharadas' }],
    steps: [{ order: 1, description: 'Desmigar pescado.' }, { order: 2, description: 'Mezclar con resto.' }, { order: 3, description: 'Hornear al baño maría.' }],
    tags: ['pescado', 'frio']
  },
  {
    id: 'nav_pr_017',
    title: 'Ensalada de Ahumados',
    description: 'Elegante.',
    category: Category.PRIMERO,
    imageUrl: getImg('smokedsalad'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'mezclum lechugas', amount: 200, unit: 'g' }, { name: 'salmón/bacalao ahumado', amount: 200, unit: 'g' }, { name: 'vinagreta', amount: 50, unit: 'ml' }],
    steps: [{ order: 1, description: 'Disponer lechugas.' }, { order: 2, description: 'Colocar ahumados y aliñar.' }],
    tags: ['frio', 'sin gluten']
  },
  {
    id: 'nav_pr_018',
    title: 'Alcachofas con Almejas',
    description: 'Mar y tierra.',
    category: Category.PRIMERO,
    imageUrl: getImg('artichokes'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'alcachofas', amount: 8, unit: 'ud' }, { name: 'almejas', amount: 300, unit: 'g' }, { name: 'vino blanco', amount: 50, unit: 'ml' }],
    steps: [{ order: 1, description: 'Cocer alcachofas.' }, { order: 2, description: 'Abrir almejas en salsa verde.' }, { order: 3, description: 'Juntar todo.' }],
    tags: ['saludable']
  },
  {
    id: 'nav_pr_019',
    title: 'Sopa de Cebolla',
    description: 'Clásico francés gratinado.',
    category: Category.PRIMERO,
    imageUrl: getImg('onionsoup'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 45,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'cebollas', amount: 4, unit: 'ud' }, { name: 'caldo carne', amount: 1, unit: 'l' }, { name: 'pan tostado', amount: 4, unit: 'rebanadas' }, { name: 'queso gruyere', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Caramelizar cebolla muy lento.' }, { order: 2, description: 'Añadir caldo y cocer.' }, { order: 3, description: 'Poner pan y queso, gratinar.' }],
    tags: ['cuchara']
  },
  {
    id: 'nav_pr_020',
    title: 'Crema de Champiñones',
    description: 'Suave y terrosa.',
    category: Category.PRIMERO,
    imageUrl: getImg('mushroomsc'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'champiñones', amount: 500, unit: 'g' }, { name: 'cebolla', amount: 1, unit: 'ud' }, { name: 'nata', amount: 100, unit: 'ml' }],
    steps: [{ order: 1, description: 'Sofreír verdura.' }, { order: 2, description: 'Cocer con agua.' }, { order: 3, description: 'Triturar con nata.' }],
    tags: ['vegetariano']
  },
  {
    id: 'nav_pr_021',
    title: 'Pimientos Rellenos de Arroz',
    description: 'Colorido.',
    category: Category.PRIMERO,
    imageUrl: getImg('stuffedpeppers'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 30,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'pimientos asar', amount: 4, unit: 'ud' }, { name: 'arroz cocido', amount: 300, unit: 'g' }, { name: 'carne picada', amount: 200, unit: 'g' }],
    steps: [{ order: 1, description: 'Mezclar arroz y carne sofrita.' }, { order: 2, description: 'Rellenar pimientos.' }, { order: 3, description: 'Hornear.' }],
    tags: ['sin gluten']
  },
  {
    id: 'nav_pr_022',
    title: 'Menestra de Verduras',
    description: 'La huerta navarra.',
    category: Category.PRIMERO,
    imageUrl: getImg('vegetables'),
    prepTimeMinutes: 30,
    cookTimeMinutes: 30,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'verduras variadas', amount: 800, unit: 'g' }, { name: 'jamón', amount: 50, unit: 'g' }, { name: 'harina', amount: 1, unit: 'cucharada' }],
    steps: [{ order: 1, description: 'Cocer verduras separadas.' }, { order: 2, description: 'Juntar en salsa con jamón.' }],
    tags: ['saludable']
  },
  {
    id: 'nav_pr_023',
    title: 'Carpaccio de Calabacín',
    description: 'Entrante crudo.',
    category: Category.PRIMERO,
    imageUrl: getImg('zucchini'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'calabacín', amount: 2, unit: 'ud' }, { name: 'parmesano', amount: 50, unit: 'g' }, { name: 'limón', amount: 1, unit: 'ud' }],
    steps: [{ order: 1, description: 'Laminar muy fino.' }, { order: 2, description: 'Macerar con limón y aceite.' }, { order: 3, description: 'Servir con queso.' }],
    tags: ['vegano', 'frio']
  },
  {
    id: 'nav_pr_024',
    title: 'Sopa Minestrone',
    description: 'Verduras italiana.',
    category: Category.PRIMERO,
    imageUrl: getImg('minestrone'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 40,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'verduras picadas', amount: 500, unit: 'g' }, { name: 'alubias', amount: 200, unit: 'g' }, { name: 'pasta corta', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Sofreír verduras.' }, { order: 2, description: 'Cocer con agua y alubias.' }, { order: 3, description: 'Añadir pasta al final.' }],
    tags: ['vegetariano', 'cuchara']
  },
  {
    id: 'nav_pr_025',
    title: 'Raviolis de Setas',
    description: 'Pasta fresca.',
    category: Category.PRIMERO,
    imageUrl: getImg('ravioli'),
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'raviolis frescos', amount: 500, unit: 'g' }, { name: 'salsa trufa', amount: 200, unit: 'ml' }, { name: 'parmesano', amount: 50, unit: 'g' }],
    steps: [{ order: 1, description: 'Cocer pasta.' }, { order: 2, description: 'Mezclar con salsa.' }],
    tags: ['vegetariano', 'pasta']
  },
  {
    id: 'nav_pr_026',
    title: 'Ensalada Waldorf',
    description: 'Manzana y apio.',
    category: Category.PRIMERO,
    imageUrl: getImg('waldorf'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'manzana', amount: 2, unit: 'ud' }, { name: 'apio', amount: 2, unit: 'ramas' }, { name: 'nueces', amount: 50, unit: 'g' }, { name: 'mayonesa', amount: 3, unit: 'cucharadas' }],
    steps: [{ order: 1, description: 'Picar manzana y apio.' }, { order: 2, description: 'Mezclar con nueces y salsa.' }],
    tags: ['vegetariano', 'frio']
  },
  {
    id: 'nav_pr_027',
    title: 'Borrajas con Almejas',
    description: 'Delicia aragonesa.',
    category: Category.PRIMERO,
    imageUrl: getImg('borage'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 20,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'borrajas', amount: 1, unit: 'kg' }, { name: 'almejas', amount: 300, unit: 'g' }, { name: 'ajo', amount: 2, unit: 'dientes' }],
    steps: [{ order: 1, description: 'Limpiar y cocer borraja.' }, { order: 2, description: 'Abrir almejas con ajo.' }, { order: 3, description: 'Juntar.' }],
    tags: ['saludable']
  },
  {
    id: 'nav_pr_028',
    title: 'Patatas a la Riojana',
    description: 'Chorizo y pimentón.',
    category: Category.PRIMERO,
    imageUrl: getImg('potatoes'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 30,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'patatas', amount: 1, unit: 'kg' }, { name: 'chorizo', amount: 1, unit: 'sarta' }, { name: 'pimentón', amount: 1, unit: 'cucharada' }],
    steps: [{ order: 1, description: 'Sofreír chorizo.' }, { order: 2, description: 'Añadir patatas cascadas.' }, { order: 3, description: 'Guisar hasta tiernas.' }],
    tags: ['tradicional', 'cuchara']
  },
  {
    id: 'nav_pr_029',
    title: 'Lentejas con Foie',
    description: 'Legumbre gourmet.',
    category: Category.PRIMERO,
    imageUrl: getImg('lentils'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 40,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'lentejas', amount: 300, unit: 'g' }, { name: 'foie mi-cuit', amount: 100, unit: 'g' }, { name: 'verduras', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Estofar lentejas con verduras.' }, { order: 2, description: 'Servir con dados de foie frío.' }],
    tags: ['cuchara']
  },
  {
    id: 'nav_pr_030',
    title: 'Crema de Guisantes con Menta',
    description: 'Fresca y verde.',
    category: Category.PRIMERO,
    imageUrl: getImg('peas'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'guisantes congelados', amount: 500, unit: 'g' }, { name: 'menta', amount: 1, unit: 'rama' }, { name: 'cebolla', amount: 1, unit: 'ud' }],
    steps: [{ order: 1, description: 'Cocer guisantes y cebolla.' }, { order: 2, description: 'Triturar con menta.' }],
    tags: ['vegano']
  },
  {
    id: 'nav_pr_031',
    title: 'Zarangollo Murciano',
    description: 'Calabacín y huevo.',
    category: Category.PRIMERO,
    imageUrl: getImg('scrambledveg'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'calabacín', amount: 2, unit: 'ud' }, { name: 'cebolla', amount: 2, unit: 'ud' }, { name: 'huevos', amount: 3, unit: 'ud' }],
    steps: [{ order: 1, description: 'Pochar verdura muy lento.' }, { order: 2, description: 'Cuajar huevos revueltos.' }],
    tags: ['vegetariano']
  },
  {
    id: 'nav_pr_032',
    title: 'Macarrones Gratinados',
    description: 'Para los peques.',
    category: Category.PRIMERO,
    imageUrl: getImg('macaroni'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'macarrones', amount: 300, unit: 'g' }, { name: 'tomate frito', amount: 200, unit: 'g' }, { name: 'chorizo', amount: 50, unit: 'g' }, { name: 'queso', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Cocer pasta.' }, { order: 2, description: 'Mezclar con tomate y chorizo.' }, { order: 3, description: 'Gratinar.' }],
    tags: ['niños']
  },
  {
    id: 'nav_pr_033',
    title: 'Gazpacho de Remolacha',
    description: 'Color navideño.',
    category: Category.PRIMERO,
    imageUrl: getImg('beetroot'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'remolacha cocida', amount: 200, unit: 'g' }, { name: 'tomates', amount: 500, unit: 'g' }, { name: 'pimiento', amount: 1, unit: 'ud' }],
    steps: [{ order: 1, description: 'Triturar todo.' }, { order: 2, description: 'Colar y enfriar.' }],
    tags: ['vegano', 'frio']
  },
  {
    id: 'nav_pr_034',
    title: 'Garbanzos con Langostinos',
    description: 'Guiso marinero.',
    category: Category.PRIMERO,
    imageUrl: getImg('chickpeas'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'garbanzos cocidos', amount: 400, unit: 'g' }, { name: 'langostinos', amount: 12, unit: 'ud' }, { name: 'caldo pescado', amount: 500, unit: 'ml' }],
    steps: [{ order: 1, description: 'Hacer sofrito con cabezas langostinos.' }, { order: 2, description: 'Añadir garbanzos y caldo.' }, { order: 3, description: 'Cuerpos al final.' }],
    tags: ['cuchara']
  },
  {
    id: 'nav_pr_035',
    title: 'Hojaldre de Espinacas y Queso',
    description: 'Tarta salada.',
    category: Category.PRIMERO,
    imageUrl: getImg('spinachpie'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'hojaldre', amount: 1, unit: 'lámina' }, { name: 'espinacas', amount: 300, unit: 'g' }, { name: 'queso cabra', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Saltear espinacas.' }, { order: 2, description: 'Poner sobre hojaldre con queso.' }, { order: 3, description: 'Hornear.' }],
    tags: ['vegetariano']
  },
  {
    id: 'nav_pr_036',
    title: 'Mousse de Pato con Oporto',
    description: 'Entrante sofisticado.',
    category: Category.PRIMERO,
    imageUrl: getImg('duckmousse'),
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'mousse pato', amount: 200, unit: 'g' }, { name: 'gelatina oporto', amount: 50, unit: 'g' }, { name: 'tostadas', amount: 1, unit: 'paquete' }],
    steps: [{ order: 1, description: 'Servir mousse con gelatina encima.' }],
    tags: ['frio']
  },
  {
    id: 'nav_pr_037',
    title: 'Tartar de Tomate',
    description: 'Fresco y vegano.',
    category: Category.PRIMERO,
    imageUrl: getImg('tomator'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'tomates buenos', amount: 4, unit: 'ud' }, { name: 'aguacate', amount: 1, unit: 'ud' }, { name: 'aliño', amount: 50, unit: 'ml' }],
    steps: [{ order: 1, description: 'Pelar y picar tomate sin semillas.' }, { order: 2, description: 'Mezclar con aguacate y aliñar.' }],
    tags: ['vegano', 'frio']
  },
  {
    id: 'nav_pr_038',
    title: 'Sopa Borsch',
    description: 'Remolacha estilo ruso.',
    category: Category.PRIMERO,
    imageUrl: getImg('borscht'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 60,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'remolacha', amount: 3, unit: 'ud' }, { name: 'repollo', amount: 200, unit: 'g' }, { name: 'caldo carne', amount: 1, unit: 'l' }, { name: 'nata agria', amount: 4, unit: 'cucharadas' }],
    steps: [{ order: 1, description: 'Cocer verduras en caldo.' }, { order: 2, description: 'Servir con nata agria.' }],
    tags: ['internacional']
  },
  {
    id: 'nav_pr_039',
    title: 'Puerros a la Vinagreta',
    description: 'Clásico francés.',
    category: Category.PRIMERO,
    imageUrl: getImg('leeks'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'puerros', amount: 8, unit: 'ud' }, { name: 'vinagreta mostaza', amount: 100, unit: 'ml' }],
    steps: [{ order: 1, description: 'Cocer puerros al dente.' }, { order: 2, description: 'Escurrir y aliñar.' }],
    tags: ['vegano', 'frio']
  },
  {
    id: 'nav_pr_040',
    title: 'Gnocchi con Salsa de Trufa',
    description: 'Pasta patata.',
    category: Category.PRIMERO,
    imageUrl: getImg('gnocchi'),
    prepTimeMinutes: 5,
    cookTimeMinutes: 5,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'gnocchi', amount: 500, unit: 'g' }, { name: 'nata', amount: 200, unit: 'ml' }, { name: 'pasta trufa', amount: 1, unit: 'cucharadita' }],
    steps: [{ order: 1, description: 'Cocer gnocchi 2 min.' }, { order: 2, description: 'Calentar nata y trufa, mezclar.' }],
    tags: ['vegetariano', 'rapido']
  },

  // ===========================================================================
  // SEGUNDOS (40 Recetas)
  // ===========================================================================
  {
    id: 'nav_sg_001',
    title: 'Cordero Asado',
    description: 'El rey de la fiesta.',
    category: Category.SEGUNDO,
    imageUrl: getImg('lamb'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 90,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'paletilla cordero', amount: 2, unit: 'ud' }, { name: 'agua', amount: 200, unit: 'ml' }, { name: 'manteca', amount: 50, unit: 'g' }],
    steps: [{ order: 1, description: 'Untar manteca.' }, { order: 2, description: 'Hornear a 180ºC volteando.' }],
    tags: ['tradicional', 'carne']
  },
  {
    id: 'nav_sg_002',
    title: 'Besugo a la Espalda',
    description: 'Pescado noble.',
    category: Category.SEGUNDO,
    imageUrl: getImg('bream'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'besugo', amount: 1, unit: 'pieza' }, { name: 'ajo', amount: 4, unit: 'dientes' }, { name: 'guindilla', amount: 1, unit: 'ud' }, { name: 'vinagre', amount: 20, unit: 'ml' }],
    steps: [{ order: 1, description: 'Hornear pescado abierto.' }, { order: 2, description: 'Echar refrito de ajos y vinagre por encima.' }],
    tags: ['pescado', 'tradicional']
  },
  {
    id: 'nav_sg_003',
    title: 'Pavo Relleno',
    description: 'Estilo americano.',
    category: Category.SEGUNDO,
    imageUrl: getImg('turkey'),
    prepTimeMinutes: 60,
    cookTimeMinutes: 180,
    difficulty: Difficulty.DIFICIL,
    servingsBase: 8,
    ingredients: [{ name: 'pavo entero', amount: 1, unit: 'ud' }, { name: 'relleno carne', amount: 500, unit: 'g' }, { name: 'frutos secos', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Rellenar.' }, { order: 2, description: 'Hornear horas regando.' }],
    tags: ['internacional', 'carne']
  },
  {
    id: 'nav_sg_004',
    title: 'Cochinillo Asado',
    description: 'Piel crujiente.',
    category: Category.SEGUNDO,
    imageUrl: getImg('piglet'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 120,
    difficulty: Difficulty.MEDIA,
    servingsBase: 6,
    ingredients: [{ name: 'cochinillo', amount: 1, unit: 'ud' }, { name: 'agua', amount: 200, unit: 'ml' }, { name: 'sal', amount: 1, unit: 'pizca' }],
    steps: [{ order: 1, description: 'Hornear sobre rejilla.' }, { order: 2, description: 'Solo agua y sal, piel arriba al final.' }],
    tags: ['tradicional', 'carne']
  },
  {
    id: 'nav_sg_005',
    title: 'Bacalao con Coliflor',
    description: 'Gallego.',
    category: Category.SEGUNDO,
    imageUrl: getImg('cod'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'bacalao', amount: 4, unit: 'lomos' }, { name: 'coliflor', amount: 0.5, unit: 'ud' }, { name: 'ajada', amount: 100, unit: 'ml' }],
    steps: [{ order: 1, description: 'Cocer coliflor.' }, { order: 2, description: 'Añadir bacalao.' }, { order: 3, description: 'Servir con ajada.' }],
    tags: ['pescado']
  },
  {
    id: 'nav_sg_006',
    title: 'Solomillo Wellington',
    description: 'Hojaldre y carne.',
    category: Category.SEGUNDO,
    imageUrl: getImg('beefwellington'),
    prepTimeMinutes: 40,
    cookTimeMinutes: 40,
    difficulty: Difficulty.DIFICIL,
    servingsBase: 4,
    ingredients: [{ name: 'solomillo ternera', amount: 800, unit: 'g' }, { name: 'hojaldre', amount: 1, unit: 'lámina' }, { name: 'duxelle setas', amount: 200, unit: 'g' }, { name: 'jamón', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Sellar carne.' }, { order: 2, description: 'Envolver en setas, jamón y hojaldre.' }, { order: 3, description: 'Hornear.' }],
    tags: ['carne', 'fiesta']
  },
  {
    id: 'nav_sg_007',
    title: 'Lubina a la Sal',
    description: 'Jugosa y sana.',
    category: Category.SEGUNDO,
    imageUrl: getImg('seabass'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 30,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'lubina entera', amount: 1, unit: 'ud' }, { name: 'sal gorda hornear', amount: 2, unit: 'kg' }],
    steps: [{ order: 1, description: 'Cubrir pescado con sal húmeda.' }, { order: 2, description: 'Hornear 30 min.' }, { order: 3, description: 'Romper costra.' }],
    tags: ['pescado', 'saludable']
  },
  {
    id: 'nav_sg_008',
    title: 'Pollo Relleno',
    description: 'Económico y rico.',
    category: Category.SEGUNDO,
    imageUrl: getImg('chicken'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 90,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'pollo entero', amount: 1, unit: 'ud' }, { name: 'ciruelas y piñones', amount: 100, unit: 'g' }, { name: 'manzana', amount: 1, unit: 'ud' }],
    steps: [{ order: 1, description: 'Rellenar pollo.' }, { order: 2, description: 'Hornear regando con jugo.' }],
    tags: ['carne']
  },
  {
    id: 'nav_sg_009',
    title: 'Wellington de Verduras',
    description: 'Vegetariano.',
    category: Category.SEGUNDO,
    imageUrl: getImg('vegwellington'),
    prepTimeMinutes: 30,
    cookTimeMinutes: 30,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'hojaldre', amount: 1, unit: 'lámina' }, { name: 'calabaza asada', amount: 200, unit: 'g' }, { name: 'setas', amount: 200, unit: 'g' }],
    steps: [{ order: 1, description: 'Rellenar hojaldre con verduras cocinadas.' }, { order: 2, description: 'Hornear.' }],
    tags: ['vegetariano']
  },
  {
    id: 'nav_sg_010',
    title: 'Merluza en Salsa Verde',
    description: 'Vasco.',
    category: Category.SEGUNDO,
    imageUrl: getImg('hake'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'rodajas merluza', amount: 4, unit: 'ud' }, { name: 'almejas', amount: 200, unit: 'g' }, { name: 'perejil', amount: 1, unit: 'manojo' }, { name: 'vino blanco', amount: 50, unit: 'ml' }],
    steps: [{ order: 1, description: 'Hacer salsa con ajo, harina y vino.' }, { order: 2, description: 'Cocer pescado y almejas en salsa.' }],
    tags: ['pescado']
  },
  {
    id: 'nav_sg_011',
    title: 'Confit de Pato',
    description: 'Francés fácil.',
    category: Category.SEGUNDO,
    imageUrl: getImg('duckconfit'),
    prepTimeMinutes: 5,
    cookTimeMinutes: 20,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'muslos confitados', amount: 4, unit: 'ud' }, { name: 'patatas', amount: 4, unit: 'ud' }],
    steps: [{ order: 1, description: 'Hornear muslos para dorar piel.' }, { order: 2, description: 'Usar grasa para saltear patatas.' }],
    tags: ['carne']
  },
  {
    id: 'nav_sg_012',
    title: 'Rape Alangostado',
    description: 'Trampantojo frío.',
    category: Category.SEGUNDO,
    imageUrl: getImg('monkfish'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 20,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'cola rape', amount: 1, unit: 'ud' }, { name: 'pimentón', amount: 1, unit: 'cucharada' }],
    steps: [{ order: 1, description: 'Untar rape en pimentón.' }, { order: 2, description: 'Cocer envuelto.' }, { order: 3, description: 'Servir rodajas frías.' }],
    tags: ['pescado', 'frio']
  },
  {
    id: 'nav_sg_013',
    title: 'Carrilleras al Vino Tinto',
    description: 'Meloso.',
    category: Category.SEGUNDO,
    imageUrl: getImg('cheeks'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 120,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'carrilleras cerdo', amount: 8, unit: 'ud' }, { name: 'vino tinto', amount: 500, unit: 'ml' }, { name: 'verduras', amount: 200, unit: 'g' }],
    steps: [{ order: 1, description: 'Sellar carne.' }, { order: 2, description: 'Guisar con verduras y vino hasta deshacerse.' }],
    tags: ['carne']
  },
  {
    id: 'nav_sg_014',
    title: 'Salmón en Croûte',
    description: 'Hojaldre de pescado.',
    category: Category.SEGUNDO,
    imageUrl: getImg('salmoncroute'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 25,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'lomo salmón', amount: 600, unit: 'g' }, { name: 'hojaldre', amount: 1, unit: 'lámina' }, { name: 'espinacas crema', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Cubrir salmón con espinacas.' }, { order: 2, description: 'Envolver en hojaldre.' }, { order: 3, description: 'Hornear.' }],
    tags: ['pescado']
  },
  {
    id: 'nav_sg_015',
    title: 'Seitan Relleno',
    description: 'Asado vegano.',
    category: Category.SEGUNDO,
    imageUrl: getImg('seitan'),
    prepTimeMinutes: 40,
    cookTimeMinutes: 60,
    difficulty: Difficulty.DIFICIL,
    servingsBase: 4,
    ingredients: [{ name: 'gluten trigo', amount: 300, unit: 'g' }, { name: 'caldo vegetal', amount: 200, unit: 'ml' }, { name: 'relleno setas', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Hacer masa seitan.' }, { order: 2, description: 'Rellenar y enrollar.' }, { order: 3, description: 'Cocer en caldo.' }],
    tags: ['vegano']
  },
  {
    id: 'nav_sg_016',
    title: 'Caldereta de Langosta',
    description: 'Menorca.',
    category: Category.SEGUNDO,
    imageUrl: getImg('lobsterstew'),
    prepTimeMinutes: 30,
    cookTimeMinutes: 45,
    difficulty: Difficulty.DIFICIL,
    servingsBase: 4,
    ingredients: [{ name: 'langosta', amount: 2, unit: 'ud' }, { name: 'sofrito', amount: 200, unit: 'g' }, { name: 'picada almendras', amount: 50, unit: 'g' }],
    steps: [{ order: 1, description: 'Trocear langosta viva.' }, { order: 2, description: 'Sofreír y cocer en salsa.' }, { order: 3, description: 'Espesar con picada.' }],
    tags: ['marisco']
  },
  {
    id: 'nav_sg_017',
    title: 'Redondo de Ternera',
    description: 'Clásico familiar.',
    category: Category.SEGUNDO,
    imageUrl: getImg('roastbeef'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 60,
    difficulty: Difficulty.MEDIA,
    servingsBase: 6,
    ingredients: [{ name: 'redondo', amount: 1, unit: 'kg' }, { name: 'cebolla', amount: 2, unit: 'ud' }, { name: 'zanahoria', amount: 2, unit: 'ud' }, { name: 'vino blanco', amount: 100, unit: 'ml' }],
    steps: [{ order: 1, description: 'Dorar pieza.' }, { order: 2, description: 'Guisar con verduras y vino.' }, { order: 3, description: 'Triturar salsa.' }],
    tags: ['carne']
  },
  {
    id: 'nav_sg_018',
    title: 'Dorada a la Sal',
    description: 'Igual que lubina.',
    category: Category.SEGUNDO,
    imageUrl: getImg('giltbream'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 30,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'dorada', amount: 1, unit: 'ud' }, { name: 'sal hornear', amount: 2, unit: 'kg' }],
    steps: [{ order: 1, description: 'Cubrir de sal.' }, { order: 2, description: 'Hornear 30 min.' }],
    tags: ['pescado']
  },
  {
    id: 'nav_sg_019',
    title: 'Chuletón de Ávila',
    description: 'Carne pura.',
    category: Category.SEGUNDO,
    imageUrl: getImg('steak'),
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    difficulty: Difficulty.FACIL,
    servingsBase: 2,
    ingredients: [{ name: 'chuletón', amount: 1, unit: 'kg' }, { name: 'sal escamas', amount: 1, unit: 'pizca' }],
    steps: [{ order: 1, description: 'Asar parrilla fuerte.' }, { order: 2, description: 'Trinchar.' }],
    tags: ['carne']
  },
  {
    id: 'nav_sg_020',
    title: 'Rodaballo al Horno',
    description: 'Pescado plano rey.',
    category: Category.SEGUNDO,
    imageUrl: getImg('turbot'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'rodaballo', amount: 1, unit: 'pieza' }, { name: 'patatas', amount: 3, unit: 'ud' }, { name: 'refrito', amount: 50, unit: 'ml' }],
    steps: [{ order: 1, description: 'Hornear sobre patatas.' }, { order: 2, description: 'Añadir refrito.' }],
    tags: ['pescado']
  },
  {
    id: 'nav_sg_021',
    title: 'Canard à l\'Orange',
    description: 'Pato a la naranja.',
    category: Category.SEGUNDO,
    imageUrl: getImg('duckorange'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 60,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'pato entero', amount: 1, unit: 'ud' }, { name: 'naranjas', amount: 3, unit: 'ud' }, { name: 'azúcar', amount: 2, unit: 'cucharadas' }],
    steps: [{ order: 1, description: 'Asar pato.' }, { order: 2, description: 'Hacer salsa gastrique con zumo y azúcar.' }],
    tags: ['internacional', 'carne']
  },
  {
    id: 'nav_sg_022',
    title: 'Zarzuela de Mariscos',
    description: 'Guiso catalán.',
    category: Category.SEGUNDO,
    imageUrl: getImg('zarzuela'),
    prepTimeMinutes: 30,
    cookTimeMinutes: 40,
    difficulty: Difficulty.DIFICIL,
    servingsBase: 4,
    ingredients: [{ name: 'pescados y mariscos variados', amount: 1, unit: 'kg' }, { name: 'picada almendra', amount: 50, unit: 'g' }, { name: 'tomate', amount: 200, unit: 'g' }],
    steps: [{ order: 1, description: 'Freír pescado.' }, { order: 2, description: 'Hacer sofrito y picada.' }, { order: 3, description: 'Guisar todo junto.' }],
    tags: ['marisco']
  },
  {
    id: 'nav_sg_023',
    title: 'Lomo de Cerdo Relleno',
    description: 'Fácil cortar.',
    category: Category.SEGUNDO,
    imageUrl: getImg('porkloin'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 60,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'cinta lomo', amount: 1, unit: 'kg' }, { name: 'queso y jamón', amount: 200, unit: 'g' }, { name: 'bacon', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Abrir lomo libro.' }, { order: 2, description: 'Rellenar, atar y asar.' }],
    tags: ['carne']
  },
  {
    id: 'nav_sg_024',
    title: 'Bacalao al Pil-Pil',
    description: 'Técnica vasca.',
    category: Category.SEGUNDO,
    imageUrl: getImg('pilpil'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    difficulty: Difficulty.DIFICIL,
    servingsBase: 4,
    ingredients: [{ name: 'bacalao', amount: 4, unit: 'tajadas' }, { name: 'aceite', amount: 300, unit: 'ml' }, { name: 'ajo', amount: 4, unit: 'dientes' }],
    steps: [{ order: 1, description: 'Confitar bacalao.' }, { order: 2, description: 'Ligar salsa moviendo cazuela.' }],
    tags: ['pescado', 'tradicional']
  },
  {
    id: 'nav_sg_025',
    title: 'Perdiz Estofada',
    description: 'Caza toledana.',
    category: Category.SEGUNDO,
    imageUrl: getImg('partridge'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 60,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'perdices', amount: 4, unit: 'ud' }, { name: 'cebolla', amount: 2, unit: 'ud' }, { name: 'vinagre', amount: 50, unit: 'ml' }],
    steps: [{ order: 1, description: 'Dorar aves.' }, { order: 2, description: 'Estofar con cebolla y vinagre.' }],
    tags: ['carne']
  },
  {
    id: 'nav_sg_026',
    title: 'Tofu al Horno Navideño',
    description: 'Glaseado.',
    category: Category.SEGUNDO,
    imageUrl: getImg('tofu'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 30,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'bloque tofu', amount: 2, unit: 'ud' }, { name: 'salsa soja', amount: 50, unit: 'ml' }, { name: 'sirope arce', amount: 2, unit: 'cucharadas' }, { name: 'clavos', amount: 10, unit: 'ud' }],
    steps: [{ order: 1, description: 'Clavar clavos en tofu.' }, { order: 2, description: 'Pintar con glaseado.' }, { order: 3, description: 'Hornear.' }],
    tags: ['vegano']
  },
  {
    id: 'nav_sg_027',
    title: 'Capón Relleno',
    description: 'Gallego Vilalba.',
    category: Category.SEGUNDO,
    imageUrl: getImg('capon'),
    prepTimeMinutes: 60,
    cookTimeMinutes: 150,
    difficulty: Difficulty.DIFICIL,
    servingsBase: 6,
    ingredients: [{ name: 'capón', amount: 1, unit: 'ud' }, { name: 'carne picada y castañas', amount: 500, unit: 'g' }],
    steps: [{ order: 1, description: 'Rellenar.' }, { order: 2, description: 'Asar lento.' }],
    tags: ['carne', 'fiesta']
  },
  {
    id: 'nav_sg_028',
    title: 'Txangurro a la Donostiarra',
    description: 'Centollo gratinado.',
    category: Category.SEGUNDO,
    imageUrl: getImg('crab'),
    prepTimeMinutes: 40,
    cookTimeMinutes: 20,
    difficulty: Difficulty.DIFICIL,
    servingsBase: 4,
    ingredients: [{ name: 'centollo', amount: 2, unit: 'ud' }, { name: 'tomate', amount: 100, unit: 'g' }, { name: 'brandy', amount: 50, unit: 'ml' }],
    steps: [{ order: 1, description: 'Cocer y sacar carne.' }, { order: 2, description: 'Mezclar con sofrito y flambear.' }, { order: 3, description: 'Gratinar en concha.' }],
    tags: ['marisco']
  },
  {
    id: 'nav_sg_029',
    title: 'Ossobuco a la Milanesa',
    description: 'Guiso italiano.',
    category: Category.SEGUNDO,
    imageUrl: getImg('ossobuco'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 120,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'morcillo con hueso', amount: 4, unit: 'ud' }, { name: 'tomate', amount: 200, unit: 'g' }, { name: 'vino blanco', amount: 100, unit: 'ml' }],
    steps: [{ order: 1, description: 'Enharinar y dorar.' }, { order: 2, description: 'Guisar.' }, { order: 3, description: 'Servir con gremolata.' }],
    tags: ['carne']
  },
  {
    id: 'nav_sg_030',
    title: 'Pastel de Carne (Shepherd\'s Pie)',
    description: 'Reconfortante.',
    category: Category.SEGUNDO,
    imageUrl: getImg('shepherdspie'),
    prepTimeMinutes: 30,
    cookTimeMinutes: 30,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'carne picada cordero', amount: 500, unit: 'g' }, { name: 'puré patata', amount: 500, unit: 'g' }, { name: 'guisantes', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Guisar carne.' }, { order: 2, description: 'Cubrir con puré.' }, { order: 3, description: 'Gratinar.' }],
    tags: ['carne']
  },
  {
    id: 'nav_sg_031',
    title: 'Trucha a la Navarra',
    description: 'Con jamón.',
    category: Category.SEGUNDO,
    imageUrl: getImg('trout'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'truchas', amount: 4, unit: 'ud' }, { name: 'lonchas jamón', amount: 4, unit: 'ud' }, { name: 'harina', amount: 50, unit: 'g' }],
    steps: [{ order: 1, description: 'Rellenar trucha con jamón.' }, { order: 2, description: 'Pasar por harina y freír.' }],
    tags: ['pescado']
  },
  {
    id: 'nav_sg_032',
    title: 'Roast Beef',
    description: 'Rosado al centro.',
    category: Category.SEGUNDO,
    imageUrl: getImg('roastbeefrare'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 40,
    difficulty: Difficulty.MEDIA,
    servingsBase: 6,
    ingredients: [{ name: 'lomo bajo', amount: 1, unit: 'kg' }, { name: 'mostaza', amount: 2, unit: 'cucharadas' }],
    steps: [{ order: 1, description: 'Sellar y untar mostaza.' }, { order: 2, description: 'Hornear a 200ºC 20 min.' }, { order: 3, description: 'Enfriar y cortar fino.' }],
    tags: ['carne', 'frio']
  },
  {
    id: 'nav_sg_033',
    title: 'Fideuá de Marisco',
    description: 'Alternativa arroz.',
    category: Category.SEGUNDO,
    imageUrl: getImg('fideua'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 20,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'fideo grueso', amount: 400, unit: 'g' }, { name: 'caldo pescado', amount: 1, unit: 'l' }, { name: 'gambas y sepia', amount: 300, unit: 'g' }],
    steps: [{ order: 1, description: 'Sofreír marisco y fideo.' }, { order: 2, description: 'Cocer en caldo.' }, { order: 3, description: 'Gratinar alioli (opcional).' }],
    tags: ['marisco']
  },
  {
    id: 'nav_sg_034',
    title: 'Lasaña de Verduras',
    description: 'Vegetariana.',
    category: Category.SEGUNDO,
    imageUrl: getImg('lasagna'),
    prepTimeMinutes: 40,
    cookTimeMinutes: 30,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'placas lasaña', amount: 12, unit: 'ud' }, { name: 'pisto', amount: 500, unit: 'g' }, { name: 'bechamel', amount: 400, unit: 'ml' }],
    steps: [{ order: 1, description: 'Montar capas pasta y pisto.' }, { order: 2, description: 'Cubrir bechamel.' }, { order: 3, description: 'Gratinar.' }],
    tags: ['vegetariano']
  },
  {
    id: 'nav_sg_035',
    title: 'Codornices en Escabeche',
    description: 'Se pueden preparar antes.',
    category: Category.SEGUNDO,
    imageUrl: getImg('quail'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 40,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'codornices', amount: 4, unit: 'ud' }, { name: 'vinagre', amount: 100, unit: 'ml' }, { name: 'vino', amount: 100, unit: 'ml' }],
    steps: [{ order: 1, description: 'Dorar.' }, { order: 2, description: 'Cocer en mezcla líquidos.' }],
    tags: ['carne']
  },
  {
    id: 'nav_sg_036',
    title: 'Ternera Strogonoff',
    description: 'Rusa cremosa.',
    category: Category.SEGUNDO,
    imageUrl: getImg('strogonoff'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 20,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'tiras solomillo', amount: 500, unit: 'g' }, { name: 'champiñones', amount: 200, unit: 'g' }, { name: 'nata agria', amount: 200, unit: 'ml' }],
    steps: [{ order: 1, description: 'Saltear carne y setas.' }, { order: 2, description: 'Añadir nata y mostaza.' }],
    tags: ['carne']
  },
  {
    id: 'nav_sg_037',
    title: 'Atún Encebollado',
    description: 'Cádiz.',
    category: Category.SEGUNDO,
    imageUrl: getImg('tuna'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 30,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'atún fresco', amount: 500, unit: 'g' }, { name: 'cebolla', amount: 3, unit: 'ud' }, { name: 'vinagre', amount: 1, unit: 'chorro' }],
    steps: [{ order: 1, description: 'Pochar mucha cebolla.' }, { order: 2, description: 'Añadir atún troceado al final.' }],
    tags: ['pescado']
  },
  {
    id: 'nav_sg_038',
    title: 'Pollo al Cava',
    description: 'Salsa festiva.',
    category: Category.SEGUNDO,
    imageUrl: getImg('cavachicken'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 40,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'pollo troceado', amount: 1, unit: 'kg' }, { name: 'cava', amount: 300, unit: 'ml' }, { name: 'cebolla', amount: 1, unit: 'ud' }],
    steps: [{ order: 1, description: 'Dorar pollo.' }, { order: 2, description: 'Guisar con cava.' }],
    tags: ['carne']
  },
  {
    id: 'nav_sg_039',
    title: 'Conejo al Ajillo',
    description: 'Tradicional.',
    category: Category.SEGUNDO,
    imageUrl: getImg('rabbit'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'conejo troceado', amount: 1, unit: 'ud' }, { name: 'ajo', amount: 1, unit: 'cabeza' }, { name: 'vino blanco', amount: 100, unit: 'ml' }],
    steps: [{ order: 1, description: 'Freír conejo.' }, { order: 2, description: 'Añadir majado ajo y vino.' }],
    tags: ['carne']
  },
  {
    id: 'nav_sg_040',
    title: 'Heura al Horno',
    description: 'Pollo vegano.',
    category: Category.SEGUNDO,
    imageUrl: getImg('heura'),
    prepTimeMinutes: 5,
    cookTimeMinutes: 15,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'bocados heura', amount: 400, unit: 'g' }, { name: 'patatas', amount: 2, unit: 'ud' }, { name: 'hierbas', amount: 1, unit: 'cucharada' }],
    steps: [{ order: 1, description: 'Asar patatas.' }, { order: 2, description: 'Añadir heura y dorar.' }],
    tags: ['vegano']
  },

  // ===========================================================================
  // POSTRES (40 Recetas)
  // ===========================================================================
  {
    id: 'nav_po_001',
    title: 'Roscón de Reyes',
    description: 'El rey.',
    category: Category.POSTRE,
    imageUrl: getImg('roscon'),
    prepTimeMinutes: 180,
    cookTimeMinutes: 20,
    difficulty: Difficulty.DIFICIL,
    servingsBase: 8,
    ingredients: [{ name: 'harina fuerza', amount: 500, unit: 'g' }, { name: 'levadura', amount: 25, unit: 'g' }, { name: 'agua azahar', amount: 20, unit: 'ml' }],
    steps: [{ order: 1, description: 'Amasar y fermentar.' }, { order: 2, description: 'Formar y fermentar.' }, { order: 3, description: 'Decorar y hornear.' }],
    tags: ['tradicional', 'bolleria']
  },
  {
    id: 'nav_po_002',
    title: 'Turrón de Chocolate',
    description: 'Crujiente.',
    category: Category.POSTRE,
    imageUrl: getImg('turronchoc'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 5,
    difficulty: Difficulty.FACIL,
    servingsBase: 6,
    ingredients: [{ name: 'chocolate', amount: 300, unit: 'g' }, { name: 'arroz inflado', amount: 50, unit: 'g' }, { name: 'manteca', amount: 30, unit: 'g' }],
    steps: [{ order: 1, description: 'Fundir.' }, { order: 2, description: 'Mezclar.' }, { order: 3, description: 'Enfriar en molde.' }],
    tags: ['dulce']
  },
  {
    id: 'nav_po_003',
    title: 'Polvorones',
    description: 'Se deshacen.',
    category: Category.POSTRE,
    imageUrl: getImg('polvoron'),
    prepTimeMinutes: 30,
    cookTimeMinutes: 15,
    difficulty: Difficulty.MEDIA,
    servingsBase: 10,
    ingredients: [{ name: 'harina tostada', amount: 250, unit: 'g' }, { name: 'manteca', amount: 125, unit: 'g' }, { name: 'almendra', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Amasar.' }, { order: 2, description: 'Cortar.' }, { order: 3, description: 'Hornear fuerte y corto.' }],
    tags: ['tradicional']
  },
  {
    id: 'nav_po_004',
    title: 'Tronco de Navidad',
    description: 'Brazo gitano.',
    category: Category.POSTRE,
    imageUrl: getImg('logcake'),
    prepTimeMinutes: 60,
    cookTimeMinutes: 15,
    difficulty: Difficulty.DIFICIL,
    servingsBase: 8,
    ingredients: [{ name: 'huevos', amount: 4, unit: 'ud' }, { name: 'chocolate', amount: 200, unit: 'g' }, { name: 'nata', amount: 200, unit: 'ml' }],
    steps: [{ order: 1, description: 'Hacer bizcocho.' }, { order: 2, description: 'Rellenar y enrollar.' }, { order: 3, description: 'Cubrir ganache.' }],
    tags: ['chocolate']
  },
  {
    id: 'nav_po_005',
    title: 'Mazapán',
    description: 'Figuritas.',
    category: Category.POSTRE,
    imageUrl: getImg('marzipan'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 5,
    difficulty: Difficulty.MEDIA,
    servingsBase: 6,
    ingredients: [{ name: 'almendra molida', amount: 200, unit: 'g' }, { name: 'azúcar glass', amount: 200, unit: 'g' }, { name: 'clara huevo', amount: 1, unit: 'ud' }],
    steps: [{ order: 1, description: 'Amasar.' }, { order: 2, description: 'Formar figuras.' }, { order: 3, description: 'Dorar al grill.' }],
    tags: ['sin gluten']
  },
  {
    id: 'nav_po_006',
    title: 'Piña Asada',
    description: 'Digestiva.',
    category: Category.POSTRE,
    imageUrl: getImg('pineapple'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'piña', amount: 1, unit: 'ud' }, { name: 'miel', amount: 2, unit: 'cucharadas' }],
    steps: [{ order: 1, description: 'Cortar.' }, { order: 2, description: 'Plancha con miel.' }],
    tags: ['fruta', 'saludable']
  },
  {
    id: 'nav_po_007',
    title: 'Galletas de Jengibre',
    description: 'Gingerbread.',
    category: Category.POSTRE,
    imageUrl: getImg('gingerbread'),
    prepTimeMinutes: 30,
    cookTimeMinutes: 12,
    difficulty: Difficulty.MEDIA,
    servingsBase: 12,
    ingredients: [{ name: 'harina', amount: 300, unit: 'g' }, { name: 'mantequilla', amount: 100, unit: 'g' }, { name: 'jengibre', amount: 1, unit: 'cucharadita' }],
    steps: [{ order: 1, description: 'Amasar.' }, { order: 2, description: 'Cortar muñecos.' }, { order: 3, description: 'Hornear.' }],
    tags: ['niños']
  },
  {
    id: 'nav_po_008',
    title: 'Panettone (Falso)',
    description: 'Muffins panettone.',
    category: Category.POSTRE,
    imageUrl: getImg('panettone'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 20,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'harina', amount: 200, unit: 'g' }, { name: 'frutas', amount: 100, unit: 'g' }, { name: 'levadura', amount: 1, unit: 'sobre' }],
    steps: [{ order: 1, description: 'Mezclar masa magdalena.' }, { order: 2, description: 'Añadir frutas.' }, { order: 3, description: 'Hornear en moldes altos.' }],
    tags: ['internacional']
  },
  {
    id: 'nav_po_009',
    title: 'Sorbete de Limón al Cava',
    description: 'Para brindar.',
    category: Category.POSTRE,
    imageUrl: getImg('sorbet'),
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'helado limón', amount: 500, unit: 'g' }, { name: 'cava', amount: 200, unit: 'ml' }],
    steps: [{ order: 1, description: 'Batir helado y cava.' }, { order: 2, description: 'Servir en copas.' }],
    tags: ['bebida']
  },
  {
    id: 'nav_po_010',
    title: 'Tarta de Santiago',
    description: 'Almendra pura.',
    category: Category.POSTRE,
    imageUrl: getImg('santiagocake'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    difficulty: Difficulty.FACIL,
    servingsBase: 8,
    ingredients: [{ name: 'almendra molida', amount: 250, unit: 'g' }, { name: 'azúcar', amount: 250, unit: 'g' }, { name: 'huevos', amount: 4, unit: 'ud' }],
    steps: [{ order: 1, description: 'Mezclar todo.' }, { order: 2, description: 'Hornear.' }, { order: 3, description: 'Espolvorear cruz.' }],
    tags: ['sin gluten', 'tradicional']
  },
  {
    id: 'nav_po_011',
    title: 'Flan de Huevo',
    description: 'Clásico.',
    category: Category.POSTRE,
    imageUrl: getImg('flan'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 40,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'huevos', amount: 4, unit: 'ud' }, { name: 'leche', amount: 500, unit: 'ml' }, { name: 'azúcar', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Caramelizar molde.' }, { order: 2, description: 'Mezclar y llenar.' }, { order: 3, description: 'Baño maría.' }],
    tags: ['sin gluten']
  },
  {
    id: 'nav_po_012',
    title: 'Arroz con Leche',
    description: 'Asturiano.',
    category: Category.POSTRE,
    imageUrl: getImg('ricepudding'),
    prepTimeMinutes: 5,
    cookTimeMinutes: 45,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'arroz redondo', amount: 100, unit: 'g' }, { name: 'leche', amount: 1, unit: 'l' }, { name: 'canela', amount: 1, unit: 'rama' }],
    steps: [{ order: 1, description: 'Cocer arroz en leche lento.' }, { order: 2, description: 'Añadir azúcar al final.' }, { order: 3, description: 'Quemar superficie.' }],
    tags: ['tradicional', 'sin gluten']
  },
  {
    id: 'nav_po_013',
    title: 'Macedonia de Invierno',
    description: 'Ligero.',
    category: Category.POSTRE,
    imageUrl: getImg('fruitsalad'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'naranja', amount: 2, unit: 'ud' }, { name: 'kiwi', amount: 2, unit: 'ud' }, { name: 'plátano', amount: 2, unit: 'ud' }, { name: 'zumo naranja', amount: 200, unit: 'ml' }],
    steps: [{ order: 1, description: 'Trocear fruta.' }, { order: 2, description: 'Macerar en zumo.' }],
    tags: ['vegano', 'saludable']
  },
  {
    id: 'nav_po_014',
    title: 'Turrón de Jijona (Blando)',
    description: 'El de toda la vida.',
    category: Category.POSTRE,
    imageUrl: getImg('turronsoft'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 0,
    difficulty: Difficulty.MEDIA,
    servingsBase: 6,
    ingredients: [{ name: 'almendra tostada', amount: 300, unit: 'g' }, { name: 'miel', amount: 200, unit: 'g' }, { name: 'azúcar', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Triturar almendra hasta sacar aceite.' }, { order: 2, description: 'Mezclar con miel caliente.' }, { order: 3, description: 'Prensado días.' }],
    tags: ['tradicional']
  },
  {
    id: 'nav_po_015',
    title: 'Peras al Vino Tinto',
    description: 'Elegante.',
    category: Category.POSTRE,
    imageUrl: getImg('pearswine'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 30,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'peras', amount: 4, unit: 'ud' }, { name: 'vino tinto', amount: 500, unit: 'ml' }, { name: 'azúcar', amount: 100, unit: 'g' }],
    steps: [{ order: 1, description: 'Pelar peras.' }, { order: 2, description: 'Cocer en vino especiado.' }],
    tags: ['fruta', 'vegano']
  },
  {
    id: 'nav_po_016',
    title: 'Pudding de Panettone',
    description: 'Aprovechamiento.',
    category: Category.POSTRE,
    imageUrl: getImg('breadpudding'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 30,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'restos panettone', amount: 300, unit: 'g' }, { name: 'leche', amount: 400, unit: 'ml' }, { name: 'huevos', amount: 3, unit: 'ud' }],
    steps: [{ order: 1, description: 'Poner trozos en molde.' }, { order: 2, description: 'Cubrir con batido huevo-leche.' }, { order: 3, description: 'Hornear.' }],
    tags: ['dulce']
  },
  {
    id: 'nav_po_017',
    title: 'Natillas Caseras',
    description: 'Con galleta.',
    category: Category.POSTRE,
    imageUrl: getImg('custard'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 15,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'yemas', amount: 4, unit: 'ud' }, { name: 'leche', amount: 500, unit: 'ml' }, { name: 'maizena', amount: 1, unit: 'cucharadita' }],
    steps: [{ order: 1, description: 'Calentar leche.' }, { order: 2, description: 'Mezclar con yemas y espesar.' }],
    tags: ['tradicional']
  },
  {
    id: 'nav_po_018',
    title: 'Coulant de Chocolate',
    description: 'Volcán.',
    category: Category.POSTRE,
    imageUrl: getImg('lavacake'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 10,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'chocolate', amount: 100, unit: 'g' }, { name: 'mantequilla', amount: 100, unit: 'g' }, { name: 'huevos', amount: 2, unit: 'ud' }, { name: 'harina', amount: 40, unit: 'g' }],
    steps: [{ order: 1, description: 'Mezclar fundido y huevos.' }, { order: 2, description: 'Hornear 10-12 min exactos.' }],
    tags: ['chocolate']
  },
  {
    id: 'nav_po_019',
    title: 'Trufas de Chocolate',
    description: 'Bocado.',
    category: Category.POSTRE,
    imageUrl: getImg('truffles'),
    prepTimeMinutes: 20,
    cookTimeMinutes: 5,
    difficulty: Difficulty.FACIL,
    servingsBase: 6,
    ingredients: [{ name: 'chocolate negro', amount: 200, unit: 'g' }, { name: 'nata', amount: 100, unit: 'ml' }, { name: 'cacao', amount: 50, unit: 'g' }],
    steps: [{ order: 1, description: 'Ganache.' }, { order: 2, description: 'Enfriar.' }, { order: 3, description: 'Bolear y rebozar cacao.' }],
    tags: ['sin gluten']
  },
  {
    id: 'nav_po_020',
    title: 'Mousse de Limón',
    description: 'Refrescante.',
    category: Category.POSTRE,
    imageUrl: getImg('lemonmousse'),
    prepTimeMinutes: 15,
    cookTimeMinutes: 0,
    difficulty: Difficulty.FACIL,
    servingsBase: 4,
    ingredients: [{ name: 'leche condensada', amount: 200, unit: 'g' }, { name: 'yogur griego', amount: 2, unit: 'ud' }, { name: 'zumo limón', amount: 100, unit: 'ml' }],
    steps: [{ order: 1, description: 'Batir todo.' }, { order: 2, description: 'Enfriar.' }],
    tags: ['rapido', 'sin gluten']
  },
  {
    id: 'nav_po_021',
    title: 'Strudel de Manzana',
    description: 'Alemán.',
    category: Category.POSTRE,
    imageUrl: getImg('strudel'),
    prepTimeMinutes: 30,
    cookTimeMinutes: 30,
    difficulty: Difficulty.MEDIA,
    servingsBase: 4,
    ingredients: [{ name: 'pasta filo', amount: 4, unit: 'hojas' }, { name: 'manzanas', amount: 3, unit: 'ud' }, { name: 'pasas', amount: 50, unit: 'g' }],
    steps: [{ order: 1, description: 'Rellenar masa con manzana.' }, { order: 2, description: 'Enrollar y pintar mantequilla.' }, { order: 3, description: 'Hornear.' }],
    tags: ['internacional']
  },
  {
    id: 'nav_po_022',
    title: 'Tarta de Queso (La Viña)',
    description: 'Cremosa.',
    category: Category.POSTRE,
    imageUrl: getImg('cheesecake'),
    prepTimeMinutes: 10,
    cookTimeMinutes: 40,
    difficulty: Difficulty.FACIL,
    servingsBase: 8,
    ingredients: [{ name: 'queso crema', amount: 500, unit: 'g' }, { name: 'nata', amount: 200, unit: 'ml' }, { name: 'azúcar', amount: 150, unit: 'g' }, { name: 'huevos', amount: